# This is a basic workflow to help you get started with Actions

name: Check Step Outcome

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get step outcome
        id: step
        run: |
          echo "this is step 1"
          exit 1
        continue-on-error: true
      - name: Check step
        run: |
          echo "C_STEP=${{ steps.step.outcome }}" >> $GITHUB_ENV

      - name: Get previous workflow TESTING
        uses: Mercymeilya/last-workflow-TESTING@v0.3.3
        id: workflow
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check workflow
        run: |
            echo "P_WORKFLOW=${{ steps.workflow.outputs.last_TESTING }}" >> $GITHUB_ENV

      - name: Testing result
        id: TESTING
        run: |
          if [[ $C_STEP == 'success' && $P_WORKFLOW == 'success' ]]; then
            echo "keepsuccess"
            echo "TESTING=keepsuccess" >> $GITHUB_ENV
          elif [[ $C_STEP == 'success' && $P_WORKFLOW == 'failure' ]]; then
            echo "backtonormal"
            echo "TESTING=backtonormal" >> $GITHUB_ENV
          elif [[ $C_STEP == 'failure' && $P_WORKFLOW == 'success' ]]; then
            echo "failure"
            echo "TESTING=failure" >> $GITHUB_ENV
          elif [[ $C_STEP == 'failure' && $P_WORKFLOW == 'failure' ]]; then
            echo "keepfailure"
            echo "TESTING=keepfailure" >> $GITHUB_ENV
          else
            echo "Unexpected condition. Investigation is required."
          fi
          
      - name: Result
        run: |
          echo "result=$TESTING"

      

