# This is a basic workflow to help you get started with Actions

name: Check Step Outcome

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      outcome: ${{ steps.outcome.outcome }}
      workflow: ${{ steps.workflow.outputs.last_status }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get step outcome
        id: outcome
        run: |
          echo "this is step 1"
          # exit 1
        continue-on-error: true
      - name: Check outcomes
        run: |
          echo "outcome=${{ steps.outcome.outcome }}"

      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.3
        id: workflow
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check workflow
        run: |
            echo "workflow=${{ steps.workflow.outputs.last_status }}"

  print:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: check

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Keep success
        if: ${{needs.check.outputs.outcome == 'success' && needs.check.outputs.workflow == 'success'}}
        run: echo "Keep success"
      
      - name: Back to normal
        if: ${{needs.check.outputs.outcome == 'success' && needs.check.outputs.workflow == 'failure'}}
        run: echo "Back to normal"
        
      - name: Failure
        if: ${{needs.check.outputs.outcome == 'failure' && needs.check.outputs.workflow == 'success'}}
        run: |
          echo "Failure"
          exit 1
        
      - name: Still failure
        if: ${{needs.check.outputs.outcome == 'failure' && needs.check.outputs.workflow == 'failure'}}
        run: |
          echo "Still failure"
          exit 1
      

