# This is a basic workflow to help you get started with Actions

name: Check Step Outcome

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: Try to fail
      #   run: exit 1
      #   continue-on-error: true
        
      - name: Step 1
        id: hello
        run: |
          echo "this is step 1"
          echo ::set-output name=status::failure
        continue-on-error: true
      - name: Step 2
        id: world
        run: |
          echo "this is step 2" 
          echo ::set-output name=status::success
        continue-on-error: true
      - name: Check outcomes
        run: |
          echo "step 1 = ${{ steps.hello.outcome }}"
          echo "step 2 = ${{ steps.world.outcome }}"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.3
        id: workflow
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check workflow
        run: echo "previous workflow = ${{ toJson(steps.workflow.outputs) }}"

      - name: Keep success
        if: ${{success()} && steps.workflow.outputs.last_status == "success"}}
        run: echo "Keep success"
      
      - name: Back to normal
        if: ${{success() && steps.workflow.outputs.last_status == "failure"}}
        run: echo "Back to normal"
        
      - name: Failure
        if: ${{failure() && steps.workflow.outputs.last_status == "success"}}
        run: echo "Failure"
        
      - name: Still failure
        if: ${{failure() && steps.workflow.outputs.last_status == "failure"}}
        run: echo "Still failure"
