# This is a basic workflow to help you get started with Actions

name: Check Step Outcome

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.status.value }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get step outcome
        id: step
        run: |
          echo "this is step 1"
          # exit 1
        continue-on-error: true
      - name: Check step
        run: |
          echo "step=${{ steps.step.outcome }}"

      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.3
        id: workflow
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check workflow
        run: |
            echo "workflow=${{ steps.workflow.outputs.last_status }}"

      - name: Testing result
        id: status
        run: |
          if [ '${{steps.step.outcome}}' == 'success' && '${{steps.workflow.outputs.last_status}}' == 'success' ]; then
            echo "keepsuccess"
            echo "value=keepsuccess" >> $GITHUB_OUTPUT
          elif [ '${{steps.step.outcome}}' == 'success' && '${{steps.workflow.outputs.last_status}}' == 'failure' ]; then
            echo "backtonormal"
            echo "value=backtonormal" >> $GITHUB_OUTPUT
          elif [ '${{steps.step.outcome}}' == 'failure' && '${{steps.workflow.outputs.last_status}}' == 'success' ]; then
            echo "failure"
            echo "value=failure" >> $GITHUB_OUTPUT
          elif [ '${{steps.step.outcome}}' == 'failure' && '${{steps.workflow.outputs.last_status}}' == 'failure' ]; then
            echo "keepfailure"
            echo "value=keepfailure" >> $GITHUB_OUTPUT
          else
            echo "none"
          fi
          
  print:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: check

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Status
        run: |
          echo "result=${{ needs.check.outputs.status }}"
          

      

