# This is a basic workflow to help you get started with Actions

name: Check Step Outcome

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Step 1
        id: step1
        run: |
          echo "this is step 1"
          exit 1
        continue-on-error: true
      - name: Check outcomes
        run: |
          echo "step 1 = ${{ steps.step1.outcome }}"

      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.3
        id: workflow
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check workflow
        run: echo "previous workflow = ${{ toJson(steps.workflow.outputs) }}"

      - name: Keep success
        if: steps.step1.outcome == 'success' && steps.workflow.outputs.last_status == 'success'
        run: echo "Keep success"
      
      - name: Back to normal
        if: steps.step1.outcome == 'success' && steps.workflow.outputs.last_status == 'failure'
        run: echo "Back to normal"
        
      - name: Failure
        if: steps.step1.outcome == 'failure' && steps.workflow.outputs.last_status == 'success'
        run: |
          echo "Failure"
          exit 1
        
      - name: Still failure
        if: steps.step1.outcome == 'failure' && steps.workflow.outputs.last_status == 'failure'
        run: |
          echo "Still failure"
          exit 1
