# This is a basic workflow to help you get started with Actions

name: Check Step Outcome

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.outcome.outcome }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get step outcome
        id: outcome
        run: |
          echo "this is step 1"
          # exit 1
        continue-on-error: true
      - name: Check outcomes
        run: |
          echo "outcome=${{ steps.outcome.outcome }}"

      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.3
        id: workflow
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check workflow
        run: |
            echo "workflow=${{ steps.workflow.outputs.last_status }}"

      - name: Keep success
        if: steps.outcome.outcome == 'success' && steps.workflow.outputs.last_statusw == 'success'
        run: echo "value=keepsuccess" >> $GITHUB_OUTPUT
      - name: Back to normal
        if: steps.outcome.outcome == 'success' && steps.workflow.outputs.last_status== 'failure'
        run: echo "value=backtonormal" >> $GITHUB_OUTPUT
      - name: Failure
        if: steps.outcome.outcome == 'failure' && steps.workflow.outputs.last_status == 'success'
        run: echo "value=failure" >> $GITHUB_OUTPUT
      - name: Still failure
        if: steps.outcome.outcome == 'failure' && steps.workflow.outputs.last_status == 'failure'
        run: echo "value=keepfailure" >> $GITHUB_OUTPUT
          
  print:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: check

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Status
        run: |
          echo "result=${{ needs.check.outputs.status }}"
          

      

